### PR TITLE
Update installation for version 6

### PR DESCRIPTION
**Pull request by ninapavlich**
I had made a pull request earlier in the week to support version 6, but missed a few places. I also updated some syntax based on feedback I got in the previous pull request.

### CODE REVIEW

**Comment by cmclaughlin** [comment]
@ninapavlich:

My colleague  @simone84 tested this and it works.  But I would recommend this:

    if elasticsearch.major_version >= 5

So the formula won't need updating when v7 is released.

**Comment by ninapavlich** [comment]
Thank you @simone84 for testing this!

@cmclaughlin I have updated the comparison method to use ">=5" rather than "in [5,6]" as you suggested. Thanks for that feedback!

**Comment by cmclaughlin** [comment]
Awesome... @blbradley would you please review?

**Comment by cmclaughlin** [comment]
Or perhaps @aboe76 or @myoung34 can review and merge?

**Comment by johnkeates** [comment]
LGTM. Feel free to merge.

**Comment by aboe76** [comment]
@ninapavlich thanks for your contribution, @cmclaughlin and @johnkeates thanks for the reviews

**Pull request merged**
