### PR TITLE
Add use_repo boolean to pillar to enable/disable ES repos

### PR DESCRIPTION
**Pull request by tedohayer**

### CODE REVIEW

**Comment by blbradley** [comment]
Hello! Thanks for your contribution.

Can you explain your rational behind this change?

**Comment by tedohayer** [comment]
We use internal yum repos here, and I didn't want the ES formula to add a repo out of our control.

This change allows you to set elasticsearch:use_repo to False in pillar to avoid setting up the official elasticsearch repo. It defaults to True.

**Comment by blbradley** [comment]
Have you seen #11? Is that what we need?

**Comment by tedohayer** [comment]
Yes I implemented in my branch before reading about #11, it's functionally the same.

**Comment by grumpydude** [comment]
I'm aware that there are now two PR's for this. It would be lovely to get one of them merged. Any update on this functionality?

**Comment by aboe76** [comment]
merged #40 instead of this one.

**Pull request closed without merging**
