### PR TITLE
[test] use sun-java-formula for Java install

### PR DESCRIPTION
**Pull request by blbradley**
Elasticsearch doesn't detect Java well. So, `JAVA_HOME` might need to be managed for this to work.

### CODE REVIEW

**Comment by blbradley** [comment]
Travis has some issues running `bundle exec *` from a bash script. I'll have to sort that out.

**Comment by blbradley** [comment]
```
*** LOCAL GEMS ***
bigdecimal (1.2.8)
bundler (1.13.6)
bundler-unload (1.0.2)
did_you_mean (1.0.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.5)
json (1.8.3)
mini_portile2 (2.1.0)
minitest (5.8.3)
net-telnet (0.1.1)
nokogiri (1.6.8.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
rvm (1.11.3.9)
test-unit (3.1.5)
```

wat

**Comment by blbradley** [comment]
This is due to some bundler behavior and the shell script. Still working on it.

**Comment by blbradley** [comment]
Using `cd` in the bash script was causing bundler not to work. If you are reading this, feel free to tell me why that happened if you have any idea.

**Comment by blbradley** [comment]
@cmclaughlin Hey! Here it is. I chose another PR cause I thought something like the mess above would happen.

The `default` suite is failing because JAVA_HOME is not set. I set that using pillar data for the other suites, but `default` is designed to test the case of not setting pillar data. I believe this points to the need of a default JAVA_HOME managed by the formula. I think I can implement that with `file.replace`. Should I implement that in this PR?

**Comment by cmclaughlin** [comment]
@blbradley sounds good... I can rebase after you merge this.

**Comment by blbradley** [comment]
`file.replace` worked well on my end. I'll merge this and update your PR when these tests are done.

**Pull request merged**
