### PR TITLE
render config pillar as config file

### PR DESCRIPTION
**Pull request by blbradley**
Hello!

I'd like to reduce the complexity of the formula via `file.serialize` to render the config pillar directly to the Elasticsearch YAML config file. This works excellently since Elasticsearch comes with great defaults.

The only issue here will be maintaining backward compatibility with `custom_options`. I haven't done there here yet but would like to try.

### CODE REVIEW

**Comment by blbradley** [comment]
@martinhoefling @kpostrup ping!

**Comment by aboe76** [comment]
@blbradley, I don't see a simple solution than to break backward compatibility....

**Comment by blbradley** [comment]
@aboe76 `elasticsearch:config:custom_options` key/values can be extracted and merged with `elasticsearch:config` with some careful Jinja. I see that as the `only` way to maintain backwards compatibility for some time.

Whether that is a good idea or not is another matter. Doing this will break someone's setup now or later, but a deprecation warning for some time would be ideal. On the other hand, users should be keeping there own forks and expecting breaking changes anytime they upgrade (which has been my feelings in practice).

**Comment by blbradley** [comment]
I should also be explict: I'm fine with breaking changes.

**Comment by blbradley** [comment]
Rebased test suite and added some conditionals to pass.

**Comment by blbradley** [comment]
@aboe76 If you choose to merge, please 'Squash and Merge'.

**Comment by blbradley** [comment]
It would be wise to add another set of tests that verify this works when `elasticsearch:config` pillar is not empty.

**Comment by aboe76** [comment]
@blbradley  so we are dropping elasticsearch.config['custom_options'] %} shouldn't this be mentioned in the README? and dropped from the pillar.example?

**Comment by blbradley** [comment]
@aboe76 You are correct. I'll look to see how other formulas show deprecation warnings in documentation.

**Comment by aboe76** [comment]
@blbradley maybe we should ping @gravyboat maybe he has some nice info on how to make an option pillar option deprecated...

**Comment by blbradley** [comment]
The only thing I could find was some formulas having a `Notes` section.

**Comment by aboe76** [comment]
@blbradley than let's do that.

**Comment by blbradley** [comment]
Feel free to add to the note if you feel it is not clear enough.

**Comment by aboe76** [comment]
Ok done, merged it.

**Comment by blbradley** [comment]
Thanks for the squash!

**Comment by simonclausen** [comment]
Good to see this change made :)

**Pull request merged**
