### PR TITLE
use key_url when hkp_port is blocked 

### PR DESCRIPTION
**Pull request by arthurlogilab**

### CODE REVIEW

**Comment by blbradley** [comment]
Hello! This is similar to #6. Can you describe why you require this?

**Comment by arthurlogilab** [comment]
I require this because the network I'm operating/deploying on has firewall restrictions for outgoing traffic, so the HKP port (11371) https://lists.gnupg.org/pipermail/gnupg-users/2003-April/017543.html is restricted. This makes the formula more flexible for these types of environments where 80/443 is allowed (or proxied) but not 11371.

**Comment by blbradley** [comment]
I understand your requirement. Can you rebase your work on the new master? So the new tests will run.

On another note, I do see some different ways to implement your change. Why did you choose this way?

**Comment by blbradley** [comment]
I encountered this problem with https://pgp.mit.edu today in another formula. It could be wiser to drop the key server and key id, and leave just the key URL.

**Comment by arthurlogilab** [comment]
@blbradley I would recommend keeping the keyid/keyserver method which in most cases is more trustworthy than keyurl. 

I'm going to rebase my PR.

**Comment by blbradley** [comment]
@arthurlogilab How is one more trustworthy than the other?

**Comment by blbradley** [comment]
You can also choose to merge from master since GitHub has the 'squash and merge' feature now.

**Comment by blbradley** [comment]
Closing due to [recommendation](https://github.com/saltstack-formulas/elasticsearch-formula/pull/6#issuecomment-267223904) in #6.

**Pull request closed without merging**
